name: IDR Alert Multi-Pair
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  check-rate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests pytz
      - run: python bot.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_USD_IDR: ${{ secrets.CHANNEL_USD_IDR }}
          CHANNEL_CNY_IDR: ${{ secrets.CHANNEL_CNY_IDR }}
          CHANNEL_SGD_IDR: ${{ secrets.CHANNEL_SGD_IDR }}
          CHANNEL_JPY_IDR: ${{ secrets.CHANNEL_JPY_IDR }}
      - name: Save last rates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add last_rate/
          git commit -m "update last rates" || echo "no changes"
          git push
